### ISSUE TITLE
PoseClustering_test fails on on Arch Linux using Clang 3.7

### ISSUE THREAD

**Issue by dstoeckel** [BALL-Project/ball#578]
PoseClustering_test fails in the the serializeWardClusterTree test with the following error message:

```
checking serializeWardClusterTree(std::ostream& out)... 
   TEST_FILE: line mismatch:
    got:      '22 serialization::archive 14 0 0 15 14 0 0 1 0 0 1 0.000000000e+00 1 0 1 1 0.000000000e+00 1 0 2 1 0.000000000e+00 1 0 3 1 0.000000000e+00 1 0 4 1 0.000000000e+00 1 0 5 1 0.000000000e+00 1 0 6 1 0.000000000e+00 1 0 7 1 0.000000000e+00 0 0 2 2.930124538e-05 0 0 3 1.017511487e+00 0 0 4 2.349177122e+00 0 0 2 9.453108311e-01 0 0 2 1.095688367e-05 0 0 4 5.062472916e+01 0 0 8 5.839497375e+01 8 1 0 0 8 0 9 3 9 8 10 2 10 9 11 7 11 6 12 4 12 5 13 12 13 11 14 13 14 10 14'
    expected: '22 serialization::archive 10 0 0 15 14 0 0 1 0 0 1 0 1 0 1 1 0 1 0 2 1 0 1 0 3 1 0 1 0 4 1 0 1 0 5 1 0 1 0 6 1 0 1 0 7 1 0 0 0 2 2.9301245e-05 0 0 3 1.0175115 0 0 4 2.3491771 0 0 2 0.94531083 0 0 2 1.0956884e-05 0 0 4 50.624729 0 0 8 58.394974 8 1 0 0 8 0 9 3 9 8 10 2 10 9 11 7 11 6 12 4 12 5 13 12 13 11 14 13 14 10 14'
    (line 1382: TEST_FILE(filename.c_str(), BALL_TEST_DATA_PATH(PoseClustering_wardtree.dat)): false - 
    FAILED
```

BALL is configured in Debug mode. I am using the following software versions:

- Clang 3.7.1
- Boost 1.60
- Eigen 3.2.8
- TBB 4.4

**Comment by tkemmer** [comment]
Ditto for Gentoo:
```
checking serializeWardClusterTree(std::ostream& out)... 
   TEST_FILE: line mismatch:
    got:      '22 serialization::archive 14 0 0 15 14 0 0 1 0 0 1 0.000000000e+00 1 0 1 1 0.000000000e+00 1 0 2 1 0.000000000e+00 1 0 3 1 0.000000000e+00 1 0 4 1 0.000000000e+00 1 0 5 1 0.000000000e+00 1 0 6 1 0.000000000e+00 1 0 7 1 0.000000000e+00 0 0 2 2.930124538e-05 0 0 3 1.017511487e+00 0 0 4 2.349177122e+00 0 0 2 9.453108311e-01 0 0 2 1.095688367e-05 0 0 4 5.062472916e+01 0 0 8 5.839497375e+01 8 1 0 0 8 0 9 3 9 8 10 2 10 9 11 7 11 6 12 4 12 5 13 12 13 11 14 13 14 10 14'
    expected: '22 serialization::archive 13 0 0 15 14 0 0 1 0 0 1 0.000000000e+00 1 0 1 1 0.000000000e+00 1 0 2 1 0.000000000e+00 1 0 3 1 0.000000000e+00 1 0 4 1 0.000000000e+00 1 0 5 1 0.000000000e+00 1 0 6 1 0.000000000e+00 1 0 7 1 0.000000000e+00 0 0 2 2.930124538e-05 0 0 3 1.017511487e+00 0 0 4 2.349177122e+00 0 0 2 9.453108311e-01 0 0 2 1.095688367e-05 0 0 4 5.062472916e+01 0 0 8 5.839497375e+01 8 1 0 0 8 0 9 3 9 8 10 2 10 9 11 7 11 6 12 4 12 5 13 12 13 11 14 13 14 10 14'
    (line 1382: TEST_FILE(filename.c_str(), BALL_TEST_DATA_PATH(PoseClustering_wardtree.dat)): false - 
    FAILED
```

* gcc 5.3.0
* Boost 1.60 (contrib)
* Eigen 3.1.3
* TBB 4.3

**Comment by philthiel** [comment]
This problem also occurs on all Linux slaves. 
However, what I'm curious about is your failure Daniel. The expected result is read from file 'PoseClustering_wardtree.dat' but the printed line does't match this file. Nevertheless, the produced result also doesn't match the expected one ; )

**Comment by philthiel** [comment]
The problem, most likely, is only a boost archive format version mismatch.
I have to double check that but the heading fields '22 serialization::archive 14' seems to be boost-internal and may change with archive format versions.

**Comment by anhi** [comment]
Yeah, that’s exactly the problem. Isn’t it possible to use regex matching in the tests when comparing to a file? We could then just replace the version string with a wildcard.


Von: philthiel <notifications@github.com<mailto:notifications@github.com>>
Antworten an: BALL-Project/ball <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 27. April 2016 um 09:32
An: BALL-Project/ball <ball@noreply.github.com<mailto:ball@noreply.github.com>>
Betreff: Re: [BALL-Project/ball] PoseClustering_test fails on on Arch Linux using Clang 3.7 (#578)


The problem, most likely, is only a boost archive format version mismatch.
I have to double check that but the heading fields '22 serialization::archive 14' seems to be boost-internal and may change with archive format versions.

**Comment by philthiel** [comment]
Under construction ...

**Comment by dstoeckel** [comment]
> This problem also occurs on all Linux slaves (different gcc versions, current ball_contrib).
However, what I'm curious about is your failure Daniel. The expected result is read from file 'PoseClustering_wardtree.dat' but the printed line does't match this file. Nevertheless, the produced result also doesn't match the expected one ; )

I suppose I was switching between branches when I ran the test and somehow got an older version of the file lying around ...

Anyhow, the regular expression fix seems appropriate.

**Comment by philthiel** [comment]
Should be fixed with commit https://github.com/BALL-Project/ball/commit/6eb56bc8408ac7dede35903fa6b856593566df6a

**Comment by dstoeckel** [comment]
Interestingly the PoseClustering_test still fails on Ubuntu 14.04 with boost 1.55, albeit for another reason. It seems that floating point numbers are encoded differently in newer versions. Oliver fixed the test for new versions in 201cd019943d6cb2e but broke it for older versions.

Probably the test should serialise and deserialise the PoseClustering object and just compare the object to the expected value instead of the string ...

**Comment by philthiel** [comment]
I'm not sure if I got your point but I think we have similar in mind: skip the file comparison, deserialize directly in the test and compare the clustertrees? If so, we simply could merge the serialize- and deserializeWardClusterTree subtests.

**Comment by dstoeckel** [comment]
Yes, that is what I meant. I would leave the deserialize test as it is (in the hope that this does not break based on the boost version) as it should make it easier to distinguish between broken serialisation and broken deserialisation.

**Comment by philthiel** [comment]
Solution commited https://github.com/BALL-Project/ball/commit/0604808e34238c87751b80c70bf7bf13eee14042 .

**Comment by dstoeckel** [comment]
Awesome! That fixes it for me.

**Comment by tkemmer** [comment]
> I would leave the deserialize test as it is (in the hope that this does not break based on the boost version) as it should make it easier to distinguish between broken serialisation and broken deserialisation.

The deserialization using boost 1.55 is indeed broken (cf. #600, confirmed), but due to Philipp's `serializeWardClusterTree` fix and boost's backwards-compatibility, the old version of the `PoseClustering_wardtree.dat` file (before Oliver's changes) should now work again for us and all boost versions since 1.55.
